export const SET_SCATTER = 'SET_SCATTER'
export const SET_EOSCLIENT = 'SET_EOSCLIENT'

export const ADD_PROPERTIES = 'ADD_PROPERTIES'
export const ADD_PROPERTY = 'ADD_PROPERTY'
export const EDIT_PROPERTY = 'EDIT_PROPERTY'
export const REMOVE_PROPERTY = 'REMOVE_PROPERTY'
